GET http://localhost:5116/games/

###
GET http://localhost:5116/games/3

###
POST http://localhost:5116/games
Content-Type: application/json

{
  "name": "Free Fire",
  "genreId": 2,
  "price": 6.99,
  "releaseDate": "2016-07-18"
}

###
PUT http://localhost:5116/games/4
Content-Type: application/json

{
  "name": "Street Fighter II Turbo",
  "genreId": "4",
  "price": 69.99,
  "releaseDate": "1992-02-01"
}

###
DELETE http://localhost:5116/games/2


